config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :genders
  resources :theme_interests
  # resources :api

  get 'api/index'
  get 'api/gender'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'api#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/theme_interest.rb
class ThemeInterest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :genders
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  # GET /theme_interests
  # GET /theme_interests.json
  def index
    @theme_interests = ThemeInterest.all
    render json: @theme_interests
  end


  def gender
    @genders = Gender.all
    render json: @genders
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  before_action :set_gender, only: [:show, :edit, :update, :destroy]

  # GET /genders
  # GET /genders.json
  def index
    @genders = Gender.all
  end

  # GET /genders/1
  # GET /genders/1.json
  def show
  end

  # GET /genders/new
  def new
    @gender = Gender.new
  end

  # GET /genders/1/edit
  def edit
  end

  # POST /genders
  # POST /genders.json
  def create
    @gender = Gender.new(gender_params)

    respond_to do |format|
      if @gender.save
        format.html { redirect_to @gender, notice: 'Gender was successfully created.' }
        format.json { render :show, status: :created, location: @gender }
      else
        format.html { render :new }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genders/1
  # PATCH/PUT /genders/1.json
  def update
    respond_to do |format|
      if @gender.update(gender_params)
        format.html { redirect_to @gender, notice: 'Gender was successfully updated.' }
        format.json { render :show, status: :ok, location: @gender }
      else
        format.html { render :edit }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genders/1
  # DELETE /genders/1.json
  def destroy
    @gender.destroy
    respond_to do |format|
      format.html { redirect_to genders_url, notice: 'Gender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gender
      @gender = Gender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gender_params
      params.require(:gender).permit(:abbreviation_1, :name, :description)
    end
end

app/controllers/theme_interests_controller.rb
class ThemeInterestsController < ApplicationController
  before_action :set_theme_interest, only: [:show, :edit, :update, :destroy]

  # GET /theme_interests
  # GET /theme_interests.json
  def index
    @theme_interests = ThemeInterest.all
  end

  # GET /theme_interests/1
  # GET /theme_interests/1.json
  def show
  end

  # GET /theme_interests/new
  def new
    @theme_interest = ThemeInterest.new
  end

  # GET /theme_interests/1/edit
  def edit
  end

  # POST /theme_interests
  # POST /theme_interests.json
  def create
    @theme_interest = ThemeInterest.new(theme_interest_params)

    respond_to do |format|
      if @theme_interest.save
        format.html { redirect_to @theme_interest, notice: 'Theme interest was successfully created.' }
        format.json { render :show, status: :created, location: @theme_interest }
      else
        format.html { render :new }
        format.json { render json: @theme_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theme_interests/1
  # PATCH/PUT /theme_interests/1.json
  def update
    respond_to do |format|
      if @theme_interest.update(theme_interest_params)
        format.html { redirect_to @theme_interest, notice: 'Theme interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme_interest }
      else
        format.html { render :edit }
        format.json { render json: @theme_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theme_interests/1
  # DELETE /theme_interests/1.json
  def destroy
    @theme_interest.destroy
    respond_to do |format|
      format.html { redirect_to theme_interests_url, notice: 'Theme interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme_interest
      @theme_interest = ThemeInterest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_interest_params
      params.require(:theme_interest).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :first_name, :genders_id)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/theme_interests_helper.rb
module ThemeInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genders/_form.html.erb
<%= form_for(gender) do |f| %>
  <% if gender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gender.errors.count, "error") %> prohibited this gender from being saved:</h2>

      <ul>
      <% gender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :abbreviation_1 %>
    <%= f.text_field :abbreviation_1 %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genders/edit.html.erb
<h1>Editing Gender</h1>

<%= render 'form', gender: @gender %>

<%= link_to 'Show', @gender %> |
<%= link_to 'Back', genders_path %>

app/views/genders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genders</h1>

<table>
  <thead>
    <tr>
      <th>Abbreviation 1</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genders.each do |gender| %>
      <tr>
        <td><%= gender.abbreviation_1 %></td>
        <td><%= gender.name %></td>
        <td><%= gender.description %></td>
        <td><%= link_to 'Show', gender %></td>
        <td><%= link_to 'Edit', edit_gender_path(gender) %></td>
        <td><%= link_to 'Destroy', gender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gender', new_gender_path %>

app/views/genders/new.html.erb
<h1>New Gender</h1>

<%= render 'form', gender: @gender %>

<%= link_to 'Back', genders_path %>

app/views/genders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abbreviation 1:</strong>
  <%= @gender.abbreviation_1 %>
</p>

<p>
  <strong>Name:</strong>
  <%= @gender.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gender.description %>
</p>

<%= link_to 'Edit', edit_gender_path(@gender) %> |
<%= link_to 'Back', genders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/theme_interests/_form.html.erb
<%= form_for(theme_interest) do |f| %>
  <% if theme_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme_interest.errors.count, "error") %> prohibited this theme_interest from being saved:</h2>

      <ul>
      <% theme_interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theme_interests/edit.html.erb
<h1>Editing Theme Interest</h1>

<%= render 'form', theme_interest: @theme_interest %>

<%= link_to 'Show', @theme_interest %> |
<%= link_to 'Back', theme_interests_path %>

app/views/theme_interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theme Interests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theme_interests.each do |theme_interest| %>
      <tr>
        <td><%= theme_interest.name %></td>
        <td><%= theme_interest.description %></td>
        <td><%= link_to 'Show', theme_interest %></td>
        <td><%= link_to 'Edit', edit_theme_interest_path(theme_interest) %></td>
        <td><%= link_to 'Destroy', theme_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme Interest', new_theme_interest_path %>

app/views/theme_interests/new.html.erb
<h1>New Theme Interest</h1>

<%= render 'form', theme_interest: @theme_interest %>

<%= link_to 'Back', theme_interests_path %>

app/views/theme_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theme_interest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @theme_interest.description %>
</p>

<%= link_to 'Edit', edit_theme_interest_path(@theme_interest) %> |
<%= link_to 'Back', theme_interests_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :genders_id %>
    <%= f.text_field :genders_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>First name</th>
      <th>Genders</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.first_name %></td>
        <td><%= user.genders %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Genders:</strong>
  <%= @user.genders %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>